<?
// *********************************************************************
//
// LinkMetro Web Solutions
//
// Source Copyright 2004-2006 Bryxen Software
// Unauthorized reproduction or editing is not allowed !
//
// *********************************************************************

$check_link_hint = "";
$check_link_page_from_LMA = 0;

function check_link($URL, $server_name, $exact = false, $redirect_level=0, $debug=0)
{
	global $check_link_hint, $check_link_page_from_LMA;		$check_link_page_from_LMA = 0;
	if ($debug) echo "<br>Try ".$redirect_level;
	@set_time_limit(30);

	if (!$exact)
	{
		$server_name = trim(strtolower($server_name));
		if (strpos($server_name, "http://") === 0) $server_name = substr($server_name, 7);
		if (strpos($server_name, "www."   ) === 0) $server_name = substr($server_name, 4);
		if (strpos($server_name, "/") !== false)
			$server_name = substr($server_name, 0, strpos($server_name, "/"));
	}

	if ($debug) echo "<br>Looking for: ".$server_name."<br>";

	while (true)
	{
		if ($redirect_level > 3)
		{
			$check_link_hint = "Operation was aborted (too many redirects)";
			return false;
		}

		if (strpos($URL, "http://") === false) $URL = 'http://'.$URL;

		$m_info = parse_url(trim($URL));
		if (empty($m_info['host']))
		{
			$check_link_hint = "The URL is not in the right format";
			return false;
		}
		if ( empty($m_info[ 'path'])) $m_info[ 'path'] = '/';
		if (!empty($m_info['query'])) $m_info['query'] = '?'.$m_info['query'];
								else  $m_info['query'] = "";


		if ($debug) echo "Trying to download... http://".$m_info['host'].$m_info['path'].$m_info['query']."<br>";
		$input = file_get_contents_http("http://".$m_info['host'].$m_info['path'].$m_info['query'], $debug, 1);
		if ($input === false)
		{
			$check_link_hint = "Cannot connect to ".$m_info['host'];
			return false;
		}

		if ($debug) echo "<br>Parsing";

		$header_end = strpos($input, "\r\n\r\n");
		$header   = substr($input, 0, $header_end);
		$document = substr($input, $header_end+4);

		if ($debug) echo "<hr>".nl2br( htmlspecialchars($header) );


		if (strpos("\n".$header, "\nLocation:") !== false)
		{
			$moved = substr($header, strpos("\n".$input, "\nLocation:") + 10);
			$moved = substr($moved, 0, strpos($moved, "\r"));
			$moved = trim($moved);
			
			if (substr($moved, 0, 7) != 'http://')
			{
			    if ($debug) echo substr($moved,0,7);
				if (substr($moved, 0, 2) == "./") $moved = "http://".$m_info['host'].substr($moved, 1);
				else {
					$dir = "http://".$m_info['host'].$m_info['path'];

					$i = 0;
					while ($j = strpos($dir, '/', $i+1))
						$i = $j;

					$moved = substr($dir, 0, $i).$moved;
				}
			}

			if ($debug) echo "<br>Moved to: ".$moved."<br>";

			if ($check_link_hint != "")
				$check_link_hint .= ";  ";
				$check_link_hint .= "The page redirected to ".$moved.". ";
			
			$URL = $moved;
			$redirect_level ++;
			continue;
		}
		break;
	}

	// parsing
	$document = str_replace(array("  ", "\r", "\n", "\t", "<", ">"), array(" ", " ", " ", " ", "\n<", ">\n"), $document);
	$document = str_replace("\n\n", "\n", $document);

	if ($debug == 2) echo "<hr>".nl2br(htmlspecialchars($document))."<hr>";

	$lines = explode("\n", $document);
	for ($i=0; $i<count($lines); $i++)
	{
		$cur       = trim($lines[$i]);
		$cur_small = strtolower($cur);

		if (strncmp($cur_small, "<!-- generated by linkmetro link directory software ", 51) == 0)
			$check_link_page_from_LMA = substr($cur, 52);

		if (strncmp($cur_small , "<a ", 3) != 0) continue;
		if (substr($cur, -1)   != ">"  ) continue;

		$href = substr($cur, strpos($cur_small, "href"));
		$href = trim(substr(strstr($href, "="), 1));

		if ($href[0] == '"' || $href[0] == "'")
		{
			$href = substr($href, 1, strpos($href, $href[0], 1)-1);
		} else if (($j = strpos($href, ' ')) !== false || ($j = strpos($href, '>')) !== false)
			$href = substr($href, 0, $j);

		$href = strtolower($href);

		if ($debug) echo "<br>Linking to ".$href;

		if ($exact)
		{
			if ($href == $server_name) { if ($debug) echo "... Found"; return true; }
		} else {
			if (strpos($href, "http://"    .$server_name.'/') === 0 || $href == "http://"    .$server_name) { if ($debug) echo "... Found"; return true; }
			if (strpos($href, "http://www.".$server_name.'/') === 0 || $href == "http://www.".$server_name) { if ($debug) echo "... Found"; return true; }
		}
	}

	if ($debug) echo "<br>";

	if (strpos( strtolower($document), "<frameset"))
		$check_link_hint = "The page appears to be a framed page. Please provide the URL of the frame that contains the link.";

	return false;
}

?>