<?
// *********************************************************************
//
// LinkMetro Web Solutions
//
// Source Copyright 2004-2006 Bryxen Software
// Unauthorized reproduction or editing is not allowed !
//
// *********************************************************************

// ------------------------------------------------------------
function GenerateLinksPage_GetLinkPage($m_site_id, $m_site_title, $m_categ_id)
{
	global $m_DB_prefix,  $m_LinksPerPage, $m_LinksOrder;

	if ($m_LinksOrder == 0) $count = dbFetch("SELECT COUNT(id) FROM ".$m_DB_prefix."links WHERE id<'"   .$m_site_id   ."' AND added_to='".$m_categ_id."' AND visible=1");
	if ($m_LinksOrder == 1) $count = dbFetch("SELECT COUNT(id) FROM ".$m_DB_prefix."links WHERE id>'"   .$m_site_id   ."' AND added_to='".$m_categ_id."' AND visible=1");
	if ($m_LinksOrder == 2) $count = dbFetch("SELECT COUNT(id) FROM ".$m_DB_prefix."links WHERE title<'".$m_site_title."' AND added_to='".$m_categ_id."' AND visible=1");

	return floor($count[0] / $m_LinksPerPage);
}

// ------------------------------------------------------------
function GenerateLinksPage_FormatSpan($m_font, $m_size, $m_color, $m_CSS_class, $m_CSS_style)
{
	$ret = '<span';

	if ($m_CSS_class != '') $ret .= ' class="'.$m_CSS_class.'"';
	if ($m_CSS_style != '' || $m_font != '' || $m_size != '' || $m_color != '') $ret .= ' style="';
	
	if ($m_CSS_style != '') $ret .= $m_CSS_style;
	if ($m_font      != '') $ret .= '; font-family:'.$m_font;
	if ($m_size      != '') $ret .= '; font-size:'.$m_size.'ex';
	if ($m_color     != '') $ret .= '; color: '.$m_color;

	if ($m_CSS_style != '' || $m_font != '' || $m_size != '' || $m_color != '') $ret .= '"';

	$ret .= '>';

	return $ret;
}

// ------------------------------------------------------------
function GenerateLinksPage($category, $generateAllChildren = false, $do_parents = true)
{
	$m_err = array();

	GenerateLinksPage_and_check_for_errors($category, $m_err, $generateAllChildren, $do_parents);

	if (count($m_err))
	{
		$string = "";

		for ($i=0; $i<count($m_err); $i++)
			$string .= "\\t".$m_err[$i]."\\n";

		echo "<script language=javaScript> alert(\"Couldn't save ".count($m_err)." files (permission denied):\\n".$string."\"); </script>";
	}
}

function GenerateLinksPage_and_check_for_errors($category, &$errors, $generateAllChildren = false, $do_parents = true)
{
	global $m_DB_prefix, $m_localTemplate, $m_localServerURL,     
		
		$m_LinksPerPage     , $m_LinksOrder       , $m_CategsOrder      , $m_SubCategsOrder       , $m_SubCategsListType,
		$m_pageShowLinkIndex, $m_pageShowLinkCount, $m_pageShowSubcategs,
		$m_pageCategFont    , $m_pageCategSize    , $m_pageCategColor   , $m_pageCategCSS_class   , $m_pageCategCSS_style   ,
		$m_pageSubCategFont , $m_pageSubCategSize , $m_pageSubCategColor, $m_pageSubCategCSS_class, $m_pageSubCategCSS_style,
		$m_pageLinkFont     , $m_pageLinkSize     , $m_pageLinkColor    , $m_pageLinkCSS_class    , $m_pageLinkCSS_style;

	$m_LinkTemplate           = ($m_pageShowLinkIndex ? "#INDEX#. " : "").GenerateLinksPage_FormatSpan($m_pageLinkFont, $m_pageLinkSize, "", $m_pageLinkCSS_class, $m_pageLinkCSS_style)."<b><a href='#URL#' target=_blank".($m_pageLinkColor != "" ? " style='color:".$m_pageLinkColor."'" : '').">#TITLE#</a></b><br>#DESC</span><br><br>\n";
	$m_CategoryTemplate       = GenerateLinksPage_FormatSpan($m_pageCategFont   , $m_pageCategSize   , $m_pageCategColor   , $m_pageCategCSS_class   , $m_pageCategCSS_style   )."<a href='#URL#'".($m_pageCategColor != "" ? " style='color:".$m_pageCategColor."'" : '')."><b>#TITLE#</b></a>".($m_pageShowLinkCount ? "&nbsp;#COUNT#":"")."</span>".($m_pageShowSubcategs ? "\n#SUBCATEGS#":"");
	$m_SubCategTemplate       = GenerateLinksPage_FormatSpan($m_pageSubCategFont, $m_pageSubCategSize, $m_pageSubCategColor, $m_pageSubCategCSS_class, $m_pageSubCategCSS_style)."<a href='#URL#'".($m_pageSubCategColor != "" ? " style='color:".$m_pageSubCategColor."'" : '').">#TITLE#</a>".($m_pageShowLinkCount ? "&nbsp;#COUNT#":"")."</span>";
	
	$m_CategoryTemplateHeader  = GenerateLinksPage_FormatSpan($m_pageCategFont, $m_pageCategSize, $m_pageCategColor, $m_pageCategCSS_class, $m_pageCategCSS_style)."<a href='#URL#'".($m_pageCategColor != "" ? " style='color:".$m_pageCategColor."'" : '')."><b>#TITLE#</b></a> &gt; </span>";
	$m_CategoryTemplate_noHref = GenerateLinksPage_FormatSpan($m_pageCategFont, $m_pageCategSize, $m_pageCategColor, $m_pageCategCSS_class, $m_pageCategCSS_style).                                                                                              "#TITLE#</span>";

	$file = "<!-- GENERATED BY LINKMETRO LINK DIRECTORY SOFTWARE ".$m_localServerURL." -->";

	// parent
	$m_category = dbFetch("SELECT parent, title, id FROM ".$m_DB_prefix."category WHERE id='".$category."'");

	if (!$generateAllChildren && $do_parents && $m_category[0] != 0)
		GenerateLinksPage_and_check_for_errors($m_category[0], $errors, $generateAllChildren, true);
	
	@set_time_limit(30);
	
	
	if ($category != 1)
		$file .= str_replace("#TITLE#", $m_category[1], $m_CategoryTemplate_noHref);

	$parent = $m_category[0];
	while ($parent)
	{
		$row = dbFetch("SELECT parent, title, id FROM ".$m_DB_prefix."category WHERE id='".$parent."'");

		$file = str_replace(array("#URL#"                             , "#TITLE#"), 
						    array(makeURL_from_categ($row[1], $row[2]), $row[1]  ), $m_CategoryTemplateHeader) . $file;

		$parent = $row[0];
	}

	// get subcategories
	$Categs_list = array();
	$curC        = dbQuery("SELECT id, title FROM ".$m_DB_prefix."category WHERE parent='".$category."' ORDER BY title");
	while ($row  = dbFetch($curC))
		$Categs_list[] = $row;

	$count = count($Categs_list);

	if ($category != 1)	$file .= "<br><br>";
	$file .= "<table cellspacing='3' cellpadding='2' width='100%'>";

	for ($indx=0; $indx<$count; $indx++)
	{
		if ($m_CategsOrder == 0) $row = $Categs_list[$indx];
		else                     $row = $Categs_list[floor($indx/3) + ceil($count * ($indx % 3) / 3)];

		if ($indx % 3 == 0) $file .= "<tr>";
		$file .= "<td valign='top' width='33%'>";

		$subCategs_list_id = array();
		$subCategs_list_tt = array();
		$subCategs_list_tc = array();
		
		$subCategs = dbQuery("SELECT id, title FROM ".$m_DB_prefix."category WHERE parent='".$row[0]."'");
		$m_count   = dbFetch("SELECT COUNT(id) FROM ".$m_DB_prefix."links WHERE added_to='".$row[0]."' AND visible=1"); $m_count = $m_count[0];
		while ($row2 = dbFetch($subCategs))
		{
			$m_count0 = 0;

			$cur_subs = array($row2[0]);
			for ($j=0; $j<count($cur_subs); $j++)
			{
				$m_count1 = dbFetch("SELECT COUNT(id) FROM ".$m_DB_prefix."links WHERE added_to='".$cur_subs[$j]."' AND visible=1");
				$m_count0 += $m_count1[0];

				$subSubCategs = dbQuery("SELECT id, title FROM ".$m_DB_prefix."category WHERE parent='".$cur_subs[$j]."'");
				while ($row3 = dbFetch($subSubCategs))
					$cur_subs[] = $row3[0];
			}

			$subCategs_list_id[] = $row2[0];
			$subCategs_list_tt[] = $row2[1];
			$subCategs_list_tc[] = $m_count0;
			$m_count += $m_count0;
		}

		if ($m_SubCategsOrder == 0) array_multisort($subCategs_list_tt, SORT_STRING , SORT_ASC , $subCategs_list_tc, SORT_NUMERIC, SORT_DESC, $subCategs_list_id);
		if ($m_SubCategsOrder == 1) array_multisort($subCategs_list_tc, SORT_NUMERIC, SORT_DESC, $subCategs_list_tt, SORT_STRING , SORT_ASC , $subCategs_list_id);

		$m_subcategs = "";
		for ($j=0; $j<count($subCategs_list_id); $j++)
		{
			if (($j ==  3 && $m_SubCategsListType % 4 == 0) || 
				($j ==  5 && $m_SubCategsListType % 4 == 1) ||
				($j == 10 && $m_SubCategsListType % 4 == 2))
			{
				$m_subcategs .= ($m_SubCategsListType < 4) ? " ..." : "<br>&nbsp;&nbsp;&nbsp;...";
				break;
			}

			if ($m_subcategs != "") $m_subcategs .= ($m_SubCategsListType < 4) ? ", " : "<br>";
			else                    $m_subcategs .= "<br>";

			if ($m_SubCategsListType >= 4) $m_subcategs .= "&nbsp;&nbsp;&nbsp;";

			$subCateg_id    = $subCategs_list_id[$j];
			$subCateg_title = $subCategs_list_tt[$j];
			$subCateg_count = $subCategs_list_tc[$j];


			$m_subcategs .= str_replace(array("#URL#", "#TITLE#", "#COUNT#"), 
											array(makeURL_from_categ($subCateg_title, $subCateg_id),
											$subCateg_title, 
											"(".$subCateg_count.")"), $m_SubCategTemplate);
		}

		$file .= str_replace(array("#URL#"                             , "#TITLE#",    "#COUNT#"    , "#SUBCATEGS#"), 
						     array(makeURL_from_categ($row[1], $row[0]), $row[1]  , "(".$m_count.")", $m_subcategs), $m_CategoryTemplate);

		$file .= "</td>";
		if ($indx % 3 == 2) $file .= "</tr><tr><td colspan='3'><br></td></tr>";
	}
	
	if ($indx % 3 != 2 && $indx) $file .= "</tr>";
	$file .= "</table><hr>\n\n";
	
	$orig_file = $file;
	if ($m_LinksOrder == 0) $order = 'id';
	if ($m_LinksOrder == 1) $order = 'id DESC';
	if ($m_LinksOrder == 2) $order = 'title';

	// get links
	$subL  = dbQuery("SELECT URL, title, `desc` FROM ".$m_DB_prefix."links WHERE added_to='".$category."' AND visible=1 ORDER BY $order");
	$indx  = 0;
	$count = mysql_num_rows($subL);
	while (true)
	{
		$row = dbFetch($subL);

		if (  ($indx && ($indx % $m_LinksPerPage) == 0) || !$row   )
		{
			$c_page = max(0, floor(($indx-1) / $m_LinksPerPage));

			if ($count > $m_LinksPerPage)
			{
				$file .= "<div align='right'>Go to page: ";

				$min = 0;
				$max = $count;


				if ($min != 0) $file .= "...";

				for ($i=$min; $i<$max; $i += $m_LinksPerPage)
				{
					if ($i)
						$file .=  ", ";

					$j = floor($i / $m_LinksPerPage);

					if ($c_page == $j) $file .= "<b>".($j+1)."</b>";
					else			   $file .= trim(str_replace(array("#URL#", "#TITLE#", "#COUNT#", "#SUBCATEGS#", "&gt;"), 
				  array(makeURL_from_categ($m_category[1], $m_category[2], $j), $j+1     , ""       , ""           , ""   ), $m_CategoryTemplateHeader));
				}
				if ($max != $count) $file .= ", ...";
				
				$file .= "</div>";
			}

			$file .= "<br><hr>";
		
			$file .= str_replace(array("#URL#"                     , "#TITLE#"                                        , "#COUNT#", "#SUBCATEGS#"), 
								 array("add_link.php?to=".$category, "Click here to add your link to our directory >>", ""       , ""           ), $m_CategoryTemplate);


			$in_file = file_get_contents_me($m_localTemplate);
			
			$i = strpos(strtolower($in_file), "</title>");
			if ($i !== false)
				$in_file = substr($in_file, 0, $i)." :: ".$m_category[1].substr($in_file, $i);

			$in_file = str_replace("#TABLE#", $file, $in_file);

			$out_file_name = makeURL_from_categ($m_category[1], $m_category[2], $c_page);

			$out_file = @fopen("../".$out_file_name, "wt");

			if ($out_file)
			{
				fwrite($out_file, $in_file);
				fclose($out_file);
			} else {
				$errors[] = $out_file_name;
			}

			$file = $orig_file;
		}

		if (empty($row)) break;

		$file .= str_replace(array("#INDEX#", "#URL#", "#TITLE#", "#DESC"), 
						     array(++$indx  , $row[0], $row[1]  , $row[2]), $m_LinkTemplate);
	}

	if ($generateAllChildren)
		for ($indx=0; $indx<count($Categs_list); $indx++)
			GenerateLinksPage_and_check_for_errors($Categs_list[$indx][0], $errors, $generateAllChildren, false);
}


?>